name: test_workflow
on: push
jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
            - name: building
              run: make setup
            - name: run tests
              run: make test
            - name: linting
              run: make lint
